version: '3.6'

networks:
  spring-cloud-network:

services:
  seeu-config:
    image: oncletom77/seeu-config
    networks:
      - spring-cloud-network

  seeu-eureka:
    image: oncletom77/seeu-eureka
    networks:
      - spring-cloud-network
    ports:
      - "${EUREKA_PORT}:8000"

  seeu-gateway:
    image: oncletom77/seeu-gateway
    networks:
      - spring-cloud-network
    ports:
      - "${GATEWAY_PORT}:8001"

  seeu-user-management:
    image: oncletom77/seeu-user-management
    networks:
      - spring-cloud-network

  seeu-team-management:
    image: oncletom77/seeu-team-management
    networks:
      - spring-cloud-network

  seeu-media-management:
    image: oncletom77/seeu-media-management
    networks:
      - spring-cloud-network

  seeu-message-management:
    image: oncletom77/seeu-message-management
    networks:
      - spring-cloud-network

  seeu-message:
    image: oncletom77/seeu-message
    networks:
      - spring-cloud-network
